/**
 * שטחי האש — רמת הגולן, אוגדה 210
 * מקור: פק"ל שטחי אש רמת הגולן, יולי 2023 (עמודי תוכן עניינים + הוראה 2)
 * נוצר: 21.04.2026
 *
 * הערות:
 * - קואורדינטות הן הערכות לצורך הדמו — לא מדויקות מבצעית
 * - כל הנתונים הם סינתטיים ומבוססים על מידע ציבורי
 * - שטחי האש האמיתיים נמצאים במסד הנתונים של "קרקע בטוחה"
 */

export const firingRanges = [
  // ─── אזור 123 — צפון ───────────────────────────────────────────────────
  {
    id: "123g",
    code: "123 ג'",
    name: "ש.א. זעורה",
    nameEn: "Zaura",
    region: "north",
    regionName: "צפון",
    lat: 33.12,
    lng: 35.78,
    type: "firing_range",
    capabilities: ["חי\"ר", "שריון", "ירי קל", "ירי כבד"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "",
  },
  {
    id: "123b",
    code: "123 ב'",
    name: "ש.א. קלע",
    nameEn: "Kela",
    region: "north",
    regionName: "צפון",
    lat: 33.10,
    lng: 35.76,
    type: "firing_range",
    capabilities: ["חי\"ר", "ירי קל", "ירי כבד"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "",
  },
  {
    id: "123a",
    code: "123 א'",
    name: "ש.א. קנעבה",
    nameEn: "Kanaba",
    region: "north",
    regionName: "צפון",
    lat: 33.08,
    lng: 35.74,
    type: "firing_range",
    capabilities: ["חי\"ר", "ירי קל"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "",
  },

  // ─── אזור 131 — צפון-מרכז (אל פוראן) ──────────────────────────────────
  {
    id: "131a",
    code: "131 א'",
    name: "ש.א. אל פוראן",
    nameEn: "Al Furan",
    region: "north_central",
    regionName: "צפון-מרכז",
    lat: 33.02,
    lng: 35.80,
    type: "firing_range",
    capabilities: ["חי\"ר", "שריון", "ירי קל", "ירי כבד", "חבלה"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "שטח ראשי — מרחב אל פוראן",
  },
  {
    id: "131a_gweirim",
    code: "131 א'",
    name: "ש.א. אל פוראן גוירים",
    nameEn: "Al Furan Gweirim",
    region: "north_central",
    regionName: "צפון-מרכז",
    lat: 33.03,
    lng: 35.82,
    type: "firing_range",
    capabilities: ["חי\"ר", "ירי קל"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "תת-שטח של אל פוראן",
  },
  {
    id: "northern",
    code: null,
    name: "ש.א. הצפוניים",
    nameEn: "Northern Ranges",
    region: "north_central",
    regionName: "צפון-מרכז",
    lat: 33.05,
    lng: 35.77,
    type: "firing_range",
    capabilities: ["חי\"ר"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "ראה מפת קוד",
  },
  {
    id: "131b",
    code: "131 ב'",
    name: "ש.א. דלווה",
    nameEn: "Dalwa",
    region: "north_central",
    regionName: "צפון-מרכז",
    lat: 32.99,
    lng: 35.83,
    type: "firing_range",
    capabilities: ["חי\"ר", "שריון", "ירי קל", "ירי כבד", "חבלה"],
    nightRestrictions: {
      noHeavyFire: { from: "23:00", to: "06:00" },
    },
    nearbySettlements: ["אורטל"],
    available: true,
    notes: "הגבלת ירי כבד וחבלה 23:00–06:00 בשל קרבת ישוב אורטל",
  },
  {
    id: "131g",
    code: "131 ג'",
    name: "ש.א. שכפי/צי דלווה",
    nameEn: "Shkafi / Tzi Dalwa",
    region: "north_central",
    regionName: "צפון-מרכז",
    lat: 32.97,
    lng: 35.84,
    type: "firing_range",
    capabilities: ["חי\"ר", "ירי קל"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "",
  },

  // ─── אזור 120 — מרכז ───────────────────────────────────────────────────
  {
    id: "120_north",
    code: "120 צ",
    name: "ש.א. 120 צפון",
    nameEn: "120 North",
    region: "central",
    regionName: "מרכז",
    lat: 32.95,
    lng: 35.85,
    type: "firing_range",
    capabilities: ["חי\"ר", "שריון", "ירי קל", "ירי כבד"],
    nightRestrictions: {
      noHeavyFire: { from: "01:00", to: "06:00" },
    },
    nearbySettlements: ["שעל", "גון"],
    available: true,
    notes: "הגבלת ירי כבד וחבלה 01:00–06:00",
  },
  {
    id: "120_center",
    code: "120 מ",
    name: "ש.א. 120 מרכז",
    nameEn: "120 Center",
    region: "central",
    regionName: "מרכז",
    lat: 32.93,
    lng: 35.86,
    type: "firing_range",
    capabilities: ["חי\"ר", "שריון", "ירי קל", "ירי כבד"],
    nightRestrictions: {
      noHeavyFire: { from: "01:00", to: "06:00" },
    },
    nearbySettlements: ["שעל", "גון"],
    available: true,
    notes: "הגבלת ירי כבד וחבלה 01:00–06:00",
  },
  {
    id: "120_south",
    code: "120 ד",
    name: "ש.א. 120 דרום",
    nameEn: "120 South",
    region: "central",
    regionName: "מרכז",
    lat: 32.91,
    lng: 35.86,
    type: "firing_range",
    capabilities: ["חי\"ר", "שריון", "ירי קל", "ירי כבד"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "",
  },
  {
    id: "120_sw",
    code: "120 דמ",
    name: "ש.א. 120 דרום מערב",
    nameEn: "120 South-West",
    region: "central",
    regionName: "מרכז",
    lat: 32.90,
    lng: 35.84,
    type: "firing_range",
    capabilities: ["חי\"ר", "ירי קל"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "",
  },
  {
    id: "120_se",
    code: "120 דז",
    name: "ש.א. 120 דרום מזרח",
    nameEn: "120 South-East",
    region: "central",
    regionName: "מרכז",
    lat: 32.90,
    lng: 35.88,
    type: "firing_range",
    capabilities: ["חי\"ר", "ירי קל"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "",
  },

  // ─── אזור 121 — מרכז-דרום (נפח / סינדיאנה) ────────────────────────────
  {
    id: "121b_east",
    code: "121 ב'",
    name: "ש.א. נפח מזרח",
    nameEn: "Nafah East",
    region: "central_south",
    regionName: "מרכז-דרום",
    lat: 32.88,
    lng: 35.90,
    type: "firing_range",
    capabilities: ["חי\"ר", "שריון", "ירי קל", "ירי כבד"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "שטח נפח — מזרחי",
  },
  {
    id: "121b_west",
    code: "121 ב'",
    name: "ש.א. נפח מערב",
    nameEn: "Nafah West",
    region: "central_south",
    regionName: "מרכז-דרום",
    lat: 32.88,
    lng: 35.87,
    type: "firing_range",
    capabilities: ["חי\"ר", "שריון", "ירי קל", "ירי כבד"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "שטח נפח — מערבי",
  },
  {
    id: "121b_ahmadia",
    code: "121 ב'",
    name: "ש.א. אחמדיה",
    nameEn: "Ahmadiya",
    region: "central_south",
    regionName: "מרכז-דרום",
    lat: 32.86,
    lng: 35.89,
    type: "firing_range",
    capabilities: ["חי\"ר", "ירי קל"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "",
  },
  {
    id: "121a_sindiana",
    code: "121 א'",
    name: "ש.א. סינדיאנה",
    nameEn: "Sindiana",
    region: "central_south",
    regionName: "מרכז-דרום",
    lat: 32.85,
    lng: 35.87,
    type: "firing_range",
    capabilities: ["חי\"ר", "שריון", "ירי קל", "ירי כבד"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "שטח ראשי — מרחב סינדיאנה",
  },
  {
    id: "121a_sindiana_mtz",
    code: "121 א'",
    name: "ש.א. מט\"ז סינדיאנה",
    nameEn: "Sindiana MTZ",
    region: "central_south",
    regionName: "מרכז-דרום",
    lat: 32.84,
    lng: 35.88,
    type: "firing_range",
    capabilities: ["חי\"ר", "מט\"ז", "ירי קל"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "מטווח מט\"ז",
  },
  {
    id: "121a_shipon",
    code: "121 א'",
    name: "ש.א. שיפון",
    nameEn: "Shifon",
    region: "central_south",
    regionName: "מרכז-דרום",
    lat: 32.83,
    lng: 35.86,
    type: "firing_range",
    capabilities: ["חי\"ר", "ירי קל"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "",
  },
  {
    id: "121a_klaot",
    code: "121 א'",
    name: "ש.א. קלעות",
    nameEn: "Klaot",
    region: "central_south",
    regionName: "מרכז-דרום",
    lat: 32.82,
    lng: 35.85,
    type: "firing_range",
    capabilities: ["חי\"ר", "ירי קל"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "",
  },
  {
    id: "121a_ramtaniot",
    code: "121 א'",
    name: "ש.א. רמתניות",
    nameEn: "Ramtaniot",
    region: "central_south",
    regionName: "מרכז-דרום",
    lat: 32.81,
    lng: 35.84,
    type: "firing_range",
    capabilities: ["חי\"ר", "ירי קל"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "",
  },
  {
    id: "121a_za_khin",
    code: "121 א'",
    name: "ש.א. זא חין",
    nameEn: "Za Khin",
    region: "central_south",
    regionName: "מרכז-דרום",
    lat: 32.80,
    lng: 35.83,
    type: "firing_range",
    capabilities: ["חי\"ר", "ירי קל"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "",
  },
  {
    id: "121a_dalhamia",
    code: "121 א'",
    name: "ש.א. דלהמיה",
    nameEn: "Dalhamiya",
    region: "central_south",
    regionName: "מרכז-דרום",
    lat: 32.79,
    lng: 35.82,
    type: "firing_range",
    capabilities: ["חי\"ר", "ירי קל"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "",
  },

  // ─── אזור 122 — דרום (גולן) ────────────────────────────────────────────
  {
    id: "122a_mishta",
    code: "122 א'",
    name: "ש.א. משתא",
    nameEn: "Mishta",
    region: "south",
    regionName: "דרום",
    lat: 32.77,
    lng: 35.81,
    type: "firing_range",
    capabilities: ["חי\"ר", "שריון", "ירי קל", "ירי כבד", "חבלה"],
    nightRestrictions: {
      noHeavyFire: { from: "01:00", to: "06:00" },
    },
    nearbySettlements: ["יונתן", "קשת"],
    available: true,
    notes: "הגבלת ירי כבד וחבלה 01:00–06:00 בשל קרבת יונתן וקשת",
  },
  {
    id: "122_shnat_krea",
    code: "122",
    name: "ש.א. שנעת קרעה",
    nameEn: "Shnat Krea",
    region: "south",
    regionName: "דרום",
    lat: 32.75,
    lng: 35.80,
    type: "firing_range",
    capabilities: ["חי\"ר", "ירי קל"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "",
  },
  {
    id: "122_golan_range",
    code: "122",
    name: "ש.א. מטווח גולן",
    nameEn: "Golan Range",
    region: "south",
    regionName: "דרום",
    lat: 32.74,
    lng: 35.79,
    type: "firing_range",
    capabilities: ["חי\"ר", "שריון", "ירי קל", "ירי כבד", "מטווח רשמי"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "מטווח רשמי — מחייב אישור מיוחד",
  },
  {
    id: "122_batandorf",
    code: "122",
    name: "ש.א. בטנדרף",
    nameEn: "Batandorf",
    region: "south",
    regionName: "דרום",
    lat: 32.73,
    lng: 35.78,
    type: "firing_range",
    capabilities: ["חי\"ר", "ירי קל", "ירי כבד"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "",
  },
  {
    id: "122_mz75",
    code: "122",
    name: "ש.א. מ\"ז 75",
    nameEn: "MZ 75",
    region: "south",
    regionName: "דרום",
    lat: 32.72,
    lng: 35.77,
    type: "firing_range",
    capabilities: ["חי\"ר", "מ\"ז 75", "ירי קל"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "מטווח מ\"ז 75",
  },
  {
    id: "122_75bn",
    code: "122",
    name: "ש.א. 75 ב\"נ ז 75",
    nameEn: "75 BN Z 75",
    region: "south",
    regionName: "דרום",
    lat: 32.71,
    lng: 35.76,
    type: "firing_range",
    capabilities: ["חי\"ר", "ירי קל"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "",
  },
  {
    id: "122b_al_arboon",
    code: "122 ב'",
    name: "ש.א. אל ארבעון",
    nameEn: "Al Arboon",
    region: "south",
    regionName: "דרום",
    lat: 32.70,
    lng: 35.75,
    type: "firing_range",
    capabilities: ["חי\"ר", "שריון", "ירי קל", "ירי כבד"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "",
  },
  {
    id: "122_nagor",
    code: "122",
    name: "ש.א. נגור",
    nameEn: "Nagor",
    region: "south",
    regionName: "דרום",
    lat: 32.69,
    lng: 35.74,
    type: "firing_range",
    capabilities: ["חי\"ר", "ירי קל"],
    nightRestrictions: null,
    nearbySettlements: [],
    available: true,
    notes: "",
  },
];

/**
 * קבוצות האזורים (לסינון ותצוגה)
 */
export const regions = [
  {
    id: "north",
    name: "צפון",
    nameEn: "North",
    codes: ["123"],
    color: "#3b82f6",
    rangeCount: 3,
  },
  {
    id: "north_central",
    name: "צפון-מרכז (אל פוראן)",
    nameEn: "North-Central (Al Furan)",
    codes: ["131"],
    color: "#8b5cf6",
    rangeCount: 5,
  },
  {
    id: "central",
    name: "מרכז (120)",
    nameEn: "Central (120)",
    codes: ["120"],
    color: "#f59e0b",
    rangeCount: 5,
  },
  {
    id: "central_south",
    name: "מרכז-דרום (נפח/סינדיאנה)",
    nameEn: "Central-South (Nafah/Sindiana)",
    codes: ["121"],
    color: "#10b981",
    rangeCount: 10,
  },
  {
    id: "south",
    name: "דרום (גולן)",
    nameEn: "South (Golan)",
    codes: ["122"],
    color: "#ef4444",
    rangeCount: 8,
  },
];

/**
 * קיבולת (capabilities) — כל הערכים האפשריים
 */
export const capabilityTypes = [
  { id: "חי\"ר", label: "חי\"ר", icon: "🪖" },
  { id: "שריון", label: "שריון", icon: "🛡️" },
  { id: "ירי קל", label: "ירי קל", icon: "🔫" },
  { id: "ירי כבד", label: "ירי כבד", icon: "💥" },
  { id: "חבלה", label: "חבלה", icon: "💣" },
  { id: "מט\"ז", label: "מט\"ז", icon: "🎯" },
  { id: "מטווח רשמי", label: "מטווח רשמי", icon: "📋" },
];

/**
 * שטח הדמו הראשי — 309ה (השטח בדמו SADAN)
 * הערה: שטח 309ה לא מופיע בפק"ל אוגדה 210 שצולם.
 * הוא מייצג שטח אימון ספציפי ברמת הגולן שנבחר לדמו.
 * הנתונים שלו הם סינתטיים.
 */
export const demoRange = {
  id: "309h",
  code: "309ה",
  name: "ש.א. 309ה",
  nameEn: "309H",
  region: "central_south",
  regionName: "מרכז-דרום",
  lat: 32.86,
  lng: 35.88,
  type: "firing_range",
  capabilities: ["חי\"ר", "שריון", "ירי קל", "ירי כבד", "חבלה"],
  nightRestrictions: null,
  nearbySettlements: [],
  area_km2: 12.5,
  maxUnits: 2,
  lastUsed: "2026-03-15",
  available: true,
  safetyGrade: "A",
  coordinates: {
    center: { lat: 32.86, lng: 35.88 },
    bounds: {
      north: 32.895,
      south: 32.825,
      east: 35.925,
      west: 35.835,
    },
  },
  notes: "שטח האימון הראשי לדמו SADAN — נבחר לאימון גדוד חי\"ר",
};
